# Generated by Django 3.1.4 on 2021-06-24 02:20

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rating',
            name='foods_ratin_created_26237c_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='recipe_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='foods_recip_created_c03d66_idx',
        ),
        migrations.AddField(
            model_name='menu',
            name='tsv',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tsv',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='menurating',
            unique_together={('user', 'menu')},
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['-updated_at'], name='foods_menu_updated_52917e_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsv'], name='foods_menu_tsv_ee5181_gin'),
        ),
        migrations.AddIndex(
            model_name='menurating',
            index=models.Index(fields=['-updated_at'], name='foods_menur_updated_7a42c0_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['-updated_at'], name='foods_ratin_updated_52a014_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['-updated_at'], name='foods_recip_updated_40a52c_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsv'], name='foods_recip_tsv_d100b8_gin'),
        ),
    ]
