# Generated by Django 3.1.4 on 2021-03-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='rating_score_gt_0',
        ),
        migrations.AddField(
            model_name='dish',
            name='image_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(check=models.Q(score__gte=0), name='rating_score_gte_0'),
        ),
    ]
