# Generated by Django 3.1.4 on 2021-01-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.FileField(upload_to='static/image/'),
        ),
    ]
