# Generated by Django 3.1.4 on 2021-01-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='score_gt_0',
        ),
        migrations.RemoveConstraint(
            model_name='rating',
            name='score_lte_5',
        ),
        migrations.AddField(
            model_name='dish',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.CheckConstraint(check=models.Q(score__gte=0), name='dish_score_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.CheckConstraint(check=models.Q(score__lte=5), name='dish_score_lte_5'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(check=models.Q(score__gt=0), name='rating_score_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(check=models.Q(score__lte=5), name='rating_score_lte_5'),
        ),
    ]
