# Generated by Django 3.1.4 on 2021-06-24 02:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('foods', '0002_auto_20210624_0920'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                CREATE FUNCTION recipes_trigger() RETURNS trigger AS $$
                begin
                      new.tsv :=
                         setweight(to_tsvector('pg_catalog.english', coalesce(new.recipe_name,'')), 'A') ||
                         setweight(to_tsvector('pg_catalog.english', coalesce(new.description,'')), 'C');
                      return new;
                end
                $$ LANGUAGE plpgsql;
                
                CREATE TRIGGER vector_column_recipe_trigger BEFORE INSERT OR UPDATE
                ON foods_recipe FOR EACH ROW EXECUTE PROCEDURE recipes_trigger();
                ''',
            reverse_sql='''
                DROP TRIGGER IF EXISTS vector_column_recipe_trigger ON foods_recipe;
                DROP FUNCTION IF EXISTS recipes_trigger;
            '''
        ),
        migrations.RunSQL(
            sql='''
              CREATE FUNCTION menus_trigger() RETURNS trigger AS $$
                begin
                      new.tsv :=
                         setweight(to_tsvector('pg_catalog.english', coalesce(new.menu_name,'')), 'A') ||
                         setweight(to_tsvector('pg_catalog.english', coalesce(new.description,'')), 'C');
                      return new;
                end
                $$ LANGUAGE plpgsql;
                
                CREATE TRIGGER vector_column_menu_trigger BEFORE INSERT OR UPDATE
                ON foods_menu FOR EACH ROW EXECUTE PROCEDURE menus_trigger();
                ''',
            reverse_sql='''
                DROP TRIGGER IF EXISTS vector_column_menu_trigger ON foods_menu;
                DROP FUNCTION IF EXISTS menus_trigger;
            '''
        )
    ]
