# Generated by Django 3.1.4 on 2020-12-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20201209_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.user'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.user'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.user'),
        ),
    ]
