# Generated by Django 3.1.4 on 2021-06-24 02:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('foods', '0002_auto_20210624_0920'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                  CREATE TRIGGER vector_column_recipe_trigger
                  BEFORE INSERT OR UPDATE ON foods_recipe
                  FOR EACH ROW EXECUTE FUNCTION
                  tsvector_update_trigger(
                    tsv, 'pg_catalog.english', recipe_name, description
                  );
                ''',
            reverse_sql='DROP TRIGGER IF EXISTS vector_column_recipe_trigger ON foods_recipe;'
        ),
        migrations.RunSQL(
            sql='''
                  CREATE TRIGGER vector_column_menu_trigger
                  BEFORE INSERT OR UPDATE ON foods_menu
                  FOR EACH ROW EXECUTE FUNCTION
                  tsvector_update_trigger(
                    tsv, 'pg_catalog.english', menu_name, description
                  );
                ''',
            reverse_sql='DROP TRIGGER IF EXISTS vector_column_menu_trigger ON foods_menu;'
        )
    ]
