# Generated by Django 3.1.4 on 2021-06-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_create_trigger'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['user'], name='foods_menu_user_id_1822c7_idx'),
        ),
        migrations.AddIndex(
            model_name='menurating',
            index=models.Index(fields=['user', 'menu'], name='foods_menur_user_id_893422_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user', 'recipe'], name='foods_ratin_user_id_23f305_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user'], name='foods_user_user_id_4ce70f_idx'),
        ),
    ]
