# Generated by Django 3.1.4 on 2021-07-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20210626_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(null=True),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['-review_number'], name='foods_menu_review__7a93f9_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['-review_number'], name='foods_recip_review__47ff45_idx'),
        ),
    ]
