# Generated by Django 3.1.4 on 2020-12-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_auto_20201221_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
    ]
