version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=hello
      - POSTGRES_PASSWORD=world123
  web:
    build: .
    command: ./startup.sh
    volumes:
      - .:/code
    ports:
      - "80:8000"
    depends_on:
      - db
