version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=hello
      - POSTGRES_PASSWORD=world123
  web:
    build: .
    command:
      - /bin/bash
      - -c
      - |
        python manage.py migrate
        python manage.py loaddata data.json
        python manage.py update_score
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "80:8000"
    depends_on:
      - db
