version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=hello
      - POSTGRES_PASSWORD=world123
  web:
    image: registry.gitlab.com/is_soict/it4421_20201/4_trinhvt:latest
    command: ./startup.sh
    volumes:
      - .:/code
    ports:
      - "80:8000"
    depends_on:
      - db
